apiVersion: v1
kind: PersistentVolume
metadata:
  name: bookstore-db-pv
  namespace: bookstore
  labels:
    type: local
spec:
  storageClassName: hostpath
  claimRef:
    name: bookstore-db-pvc
    namespace: bookstore
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  hostPath: 
    path: "/database"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: bookstore-be-pv
  namespace: bookstore
  labels:
    type: local
spec:
  storageClassName: hostpath
  claimRef:
    name: bookstore-be-pvc
    namespace: bookstore
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  hostPath: 
    path: "/images"
