apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-depl
  namespace: bookstore
  labels:
    app: fe-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fe-depl
  template:
    metadata:
      labels:
        app: fe-depl
    spec:
      containers:
      - name: fe-depl
        image: manifest_bookstore-frontend
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_PROXY_HOST
          value: "localhost"
        - name: REACT_APP_PROXY_PORT
          value: "3001"
---
apiVersion: v1
kind: Service
metadata:
  name: fe-svc
spec:
  selector:
    app: fe-depl
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: http
