apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bookstore-db-pvc
  namespace: bookstore
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
--- 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bookstore-be-pvc
  namespace: bookstore
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
